# azure-pipelines.yml
trigger:
- '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: DeployWebsite
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Install .NET Core SDK'

  - script: dotnet tool install -g bicep
    displayName: 'Install Bicep CLI'

  - script: bicep build templates/main.bicep
    displayName: 'Build Bicep template'

  - task: CopyFiles@2
    inputs:
      SourceFolder: 'website'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/website'
    displayName: 'Copy website files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/website'
      ArtifactName: 'website'
    displayName: 'Publish website artifacts'

- job: DeployBlueEnvironment
  steps:
  - ... # Steps to build and deploy the "blue" environment

- job: ValidateBlueEnvironment
  dependsOn: DeployBlueEnvironment
  steps:
  - ... # Steps to run Pester tests against the "blue" environment

- job: DeployGreenEnvironment
  dependsOn: ValidateBlueEnvironment
  steps:
  - ... # Steps to build and deploy the "green" environment

- job: SwapTraffic
  dependsOn: DeployGreenEnvironment
  steps:
  - script: az network traffic-manager endpoint set-status --name <your-traffic-manager-profile-name> --resource-group <your-resource-group> --type azureEndpoints --endpoint-name <your-endpoint-name> --status Enabled
    displayName: 'Enable Traffic to Green Environment'
    env:
      AZURE_CLI_DISABLE_CONNECTION_VERIFICATION: 'true'
